config/routes.rb
Rails.application.routes.draw do

  # Load devise routes and use custom registration controller.
  devise_for :users, controllers: { registrations: 'devise_custom/registrations', sessions: 'devise_custom/sessions' }

  # GET
  get 'finances/dashboard', to: 'finances#dashboard', as: 'dashboard' # This is the post-auth path for users.
  get 'finances/income'
  get 'finances/one-time-transactions'
  get 'finances/recurring-transactions'

  get '/password_requirements', to: 'users#get_password_requirements'

  # POST
  post '/set_session_captcha', to: 'captcha#setSessionCaptcha'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Set the root route to the prebuilt devise login page.
  devise_scope :user do
    root to: "devise/sessions#new", as: 'sign_out'
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord

  PASSWORD_REQUIREMENTS = {
    minimum_capital_letters:    1,
    minimum_lower_case_letters: 1,
    minimum_numbers:            1,
    minimum_special_characters: 1,
    valid_special_characters:   "!@#\$%\^&\*"
  }.freeze

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :timeoutable

  validates :password, password_complexity: true
  validates :email, email_format: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, unless: -> { devise_controller? || captcha_storage_request? || get_password_requirements? }
    before_action :verify_captcha, unless: -> { user_signed_in? || captcha_storage_request? || get_password_requirements? }
  
    def after_sign_in_path_for(resource)
      # return the path based on resource
      dashboard_path
    end
  
    private
  
    def verify_captcha
        CaptchaController.new.verifyCaptcha(session[:captcha_response])
    end

    def captcha_storage_request?
      request.path == '/set_session_captcha' && request.post?
    end

    def get_password_requirements?
      request.path == '/password_requirements' && request.get?
    end
  end

app/controllers/captcha_controller.rb
require 'net/http'
require 'uri'
require 'json'

class CaptchaController < ApplicationController
  def verifyCaptcha(captcha_response)

    return false if captcha_response.nil? || captcha_response.empty?

    # Rails.logger.info("Captcha token: #{captcha_response}")
    # Rails.logger.info("Captcha secret: #{ENV['CAPTCHA_SECRET_KEY']}")
  
    uri = URI.parse("https://challenges.cloudflare.com/turnstile/v0/siteverify")
    request = Net::HTTP::Post.new(uri)
    request.set_form_data(
      "secret" => ENV['CAPTCHA_SECRET_KEY'],
      "response" => captcha_response,
    )

    req_options = {
      use_ssl: uri.scheme == "https",
    }

    response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
      http.request(request)
    end

    data = JSON.parse(response.body)

    # Rails.logger.info("Captcha response: #{data}")

    return data['success']
  end

  def setSessionCaptcha
    session[:captcha_response] = params[:token]
    head :ok
  end
end

app/controllers/devise_custom/registrations_controller.rb
module DeviseCustom
  class RegistrationsController < Devise::RegistrationsController
    def build_resource(*args)
      super
      @minimum_password_length = Devise.password_length.min
      @maximum_password_length = Devise.password_length.max
      # All other requirements are specified in app\validators\password_complexity_validator.rb
    end
  end
end

app/controllers/devise_custom/sessions_controller.rb
module DeviseCustom
    class SessionsController < Devise::SessionsController

        # On session creation (sign in), ensures the users CAPTCHA token is legit by verifying server-side.
        def create
            self.resource = warden.authenticate!(auth_options)
            if verifyCaptcha
              set_flash_message!(:notice, :signed_in)
              sign_in(resource_name, resource)
              yield resource if block_given?
              respond_with resource, location: after_sign_in_path_for(resource)
            else
              sign_out(resource_name)
              flash[:alert] = "CAPTCHA Verification Failed"
              redirect_to sign_out_path
            end
        end
    
        private
    
        def verifyCaptcha
            return CaptchaController.new.verifyCaptcha(session[:captcha_response])
        end
    end
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  def dashboard
  end
  def income
  end
  def one_time_transactions
  end
  def recurring_transactions
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    def build_resource(*args)
      super
      @minimum_password_length = Devise.password_length.min
      @maximum_password_length = Devise.password_length.max
    end
  end
end

app/controllers/users/sessions_controller.rb
module Users
    class SessionsController < Devise::SessionsController
        def create
            self.resource = warden.authenticate!(auth_options)
            if verifyCaptcha
              set_flash_message!(:notice, :signed_in)
              sign_in(resource_name, resource)
              yield resource if block_given?
              respond_with resource, location: after_sign_in_path_for(resource)
            else
              sign_out(resource_name)
              flash[:alert] = "CAPTCHA Verification Failed"
              redirect_to sign_out_path
            end
        end
    
        private
    
        def verifyCaptcha
            return CaptchaController.new.verifyCaptcha(session[:captcha_response])
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def edit
      @user = current_user
    end
  
    def update
      @user = current_user
      if @user.update(user_params)
        redirect_to edit_user_path, notice: 'Profile Updated Successfully'
      else
        render :edit
      end
    end

    def get_password_requirements
        custom_requirements = User::PASSWORD_REQUIREMENTS;
        requirements = {
            minimum: Devise.password_length.min,
            maximum: Devise.password_length.max,
            uppercase: custom_requirements[:minimum_capital_letters],
            lowercase: custom_requirements[:minimum_lower_case_letters],
            numbers: custom_requirements[:minimum_numbers],
            special_characters: custom_requirements[:minimum_special_characters],
            valid_special_characters: custom_requirements[:valid_special_characters]
        }

        render json: requirements
    end
  
    private
  
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/views/finances/dashboard.html.erb
<h1 class="text-3xl font-bold">Goodbye World!</h1>

app/views/finances/income.html.erb
Income!

app/views/finances/one_time_transactions.html.erb
One-Time Transactions!

app/views/finances/recurring_transactions.html.erb
Recurring Transactions!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finances Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-neutral-900 text-neutral-400">
    <%= render 'shared/navigation' %>
    <main class="mx-14 mt-14">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_captcha.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback" defer></script>
<script>
  window.onloadTurnstileCallback = function () {
    turnstile.render('#cloudflare-captcha', {
        sitekey: '0x4AAAAAAAQOOJsyhCP1ol-S',
        callback: function(token) {
          $.ajax({
            url: '/set_session_captcha',
            type: 'post',
            data: { token: token },
            headers: {
              'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
            },
            success: function() {
              // console.log("CAPTCHA token stored successfully");
            },
            error: function() {
              // console.log("CAPTCHA token could not be stored");
            }
          });
        },
    });
  };
</script>

<div class="mt-4" id="cloudflare-captcha"></div>

app/views/shared/_navigation.html.erb
<script>
  document.addEventListener('DOMContentLoaded', (event) => {
    // Get the button that opens the dropdown
    const dropdownButton = document.getElementById('user-menu-button');
    const mobileDropdownButton = document.getElementById('mobile-user-menu-button');

    // Get the dropdown menu
    const dropdownMenu = document.getElementById('user-menu');
    const mobileDropdownMenu = document.getElementById('mobile-user-menu');

    // Toggle the display of the dropdown menu when the button is clicked
    if (dropdownButton != null && dropdownMenu != null) {
      dropdownButton.addEventListener('click', (event) => {
        event.stopPropagation(); // Prevent the document click event from firing
        if (dropdownMenu.classList.contains('menu-hidden')) {
          dropdownMenu.classList.remove('menu-hidden');
          dropdownMenu.classList.add('menu-shown');
        } else {
          dropdownMenu.classList.remove('menu-shown');
          dropdownMenu.classList.add('menu-hidden');
        }
      });
      
      // Hide the dropdown menu when the document is clicked
      document.addEventListener('click', () => {
        if (dropdownMenu.classList.contains('menu-shown')) {
          dropdownMenu.classList.remove('menu-shown');
          dropdownMenu.classList.add('menu-hidden');
        }
      });

      // Prevent the document click event from firing when the dropdown menu is clicked
      dropdownMenu.addEventListener('click', (event) => {
        event.stopPropagation();
      });
    }
  });
</script>
<nav class="bg-green-950">
    <div class="mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 items-center justify-between">
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <img class="h-8 w-8" src="https://tailwindui.com/img/logos/mark.svg?color=gray&shade=900" alt="Your Company">
          </div>
          <div class="hidden md:block">
            <div class="ml-10 flex items-baseline space-x-4">
              <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
              <%= link_to "Dashboard", dashboard_path, class:"nav-link" %>
              <%= link_to "Manage One-Time Spending", finances_one_time_transactions_path, class:"nav-link" %>
              <%= link_to "Manage Recurring Spending", finances_recurring_transactions_path, class:"nav-link" %>
              <%= link_to "Manage Income", finances_income_path, class:"nav-link" %>
            </div>
          </div>
        </div>
        <% if current_user %>
        <div class="hidden md:block">
          <div class="ml-4 flex items-center md:ml-6">
            <button type="button" class="relative rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
              <span class="absolute -inset-1.5"></span>
              <span class="sr-only">View notifications</span>
              <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
              </svg>
            </button>

            <!-- Profile dropdown -->
            <div class="relative ml-3">
              <div>
                <button type="button" class="relative flex max-w-xs items-center rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                  <span class="absolute -inset-1.5"></span>
                  <span class="sr-only">Open user menu</span>
                  <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                </button>
              </div>

              <!--
                Dropdown menu, show/hide based on menu state.

                Entering: "transition ease-out duration-100"
                  From: "transform opacity-0 scale-95"
                  To: "transform opacity-100 scale-100"
                Leaving: "transition ease-in duration-75"
                  From: "transform opacity-100 scale-100"
                  To: "transform opacity-0 scale-95"
              -->
              <div class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none menu-hidden" role="menu" aria-orientation="vertical" id="user-menu" aria-labelledby="user-menu-button" tabindex="-1">
                <!-- Active: "bg-gray-100", Not Active: "" -->
                <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>
                <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a>
                <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'block px-4 py-2 text-sm text-gray-700' %>
              </div>
          </div>
        </div>
        <div class="-mr-2 flex md:hidden">
          <!-- Mobile menu button -->
          <button type="button" class="relative inline-flex items-center justify-center rounded-md bg-gray-800 p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" aria-controls="mobile-menu" aria-expanded="false">
            <span class="absolute -inset-0.5"></span>
            <span class="sr-only">Open main menu</span>
            <!-- Menu open: "hidden", Menu closed: "block" -->
            <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
            <!-- Menu open: "block", Menu closed: "hidden" -->
            <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>
    </div>
    <% else %>
      <%= link_to 'Sign In', new_user_session_path, class: 'block rounded-md px-3 py-2 text-base font-medium text-gray-400 hover:bg-gray-700 hover:text-white' %>
    <% end %>

    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="md:hidden" id="mobile-menu">
      <div class="space-y-1 px-2 pb-3 pt-2 sm:px-3">
        <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
        <%= link_to "Dashboard", dashboard_path, class:"nav-link" %>
        <%= link_to "Manage One-Time Spending", finances_one_time_transactions_path, class:"nav-link" %>
        <%= link_to "Manage Recurring Spending", finances_recurring_transactions_path, class:"nav-link" %>
        <%= link_to "Manage Income", finances_income_path, class:"nav-link" %>
      </div>
      <% if current_user %>
      <div class="border-t border-gray-700 pb-3 pt-4">
        <div class="flex items-center px-5">
          <div class="flex-shrink-0">
            <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
          </div>
          <div class="ml-3">
            <div class="text-base font-medium leading-none text-white">Tom Cook</div>
            <div class="text-sm font-medium leading-none text-gray-400">tom@example.com</div>
          </div>
          <button type="button" id="mobile-user-menu-button" class="relative ml-auto flex-shrink-0 rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
            <span class="absolute -inset-1.5"></span>
            <span class="sr-only">View notifications</span>
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
            </svg>
          </button>
        </div>
        <div class="mt-3 space-y-1 px-2" id="mobile-user-menu">
          <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-400 hover:bg-gray-700 hover:text-white">Your Profile</a>
          <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-400 hover:bg-gray-700 hover:text-white">Settings</a>
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'block rounded-md px-3 py-2 text-base font-medium text-gray-400 hover:bg-gray-700 hover:text-white' %>        </div>
      </div>
    </div>
    <% else %>
      <%= link_to 'Sign In', new_user_session_path, class: 'block rounded-md px-3 py-2 text-base font-medium text-gray-400 hover:bg-gray-700 hover:text-white' %>
    <% end %>
</nav>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
    <div>
      <%= f.label :email %><br />
      <%= f.email_field :email %>
    </div>
  
    <div>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
  
    <div>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
  
    <%= f.submit 'Update Profile' %>
  <% end %>
  
  <%= link_to 'Enable 2FA via Email', enable_email_two_factor_users_path %>
  <%= link_to 'Enable 2FA via Phone', enable_phone_two_factor_users_path %>
  <%= link_to 'Enable 2FA via Authenticator App', enable_auth_app_two_factor_users_path %>